### ISSUE TITLE
Robot occasionally turns when driving forward

### ISSUE THREAD

**Issue by Linkd-Aether** [FRCTeam1073-TheForceTeam/robot19_VSCode#24]
When pressing up or down on the control stick, occasionally the left side (the side with the compressor) drives while the other side does not. Both sides' Talons display that they are running at the same speed. This issue appears unable to be replicated intentionally, but it is not an uncommon occurrence.

**Comment by JoshRobey** [comment]
It had nothing to do with code and everything to do with chipped pinion gears
